# Generated by Django 6.0.1 on 2026-01-10 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_addmoney_info_id_alter_userprofile_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='addmoney_info',
            table='addmoney',
        ),
    ]
