# Generated by Django 6.0.1 on 2026-02-20 15:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_recurringexpense_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringexpense',
            name='start_date',
        ),
        migrations.AddField(
            model_name='recurringexpense',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
